const fs = require('fs');
const admin = require("firebase-admin");

const serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();
const data = JSON.parse(fs.readFileSync('flashcards.json'));

data.forEach(async (item) => {
  const docRef = db.collection('cards').doc(); 
  await docRef.set(item);
  console.log(`Document with autogenerated ID ${docRef.id} added`);
});
