const fs = require('fs');
const admin = require("firebase-admin");

const serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

// Read the JSON file
const data = JSON.parse(fs.readFileSync('flashcards.json'));

// Import the data into Firestore with autogenerated IDs
data.forEach(async (item) => {
  const docRef = db.collection('cards').doc(); // no argument => auto ID
  await docRef.set(item);
  console.log(`Document with autogenerated ID ${docRef.id} added`);
});
